C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 495 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 872 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 90 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 607 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 263 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 388 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 93 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 57 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 693 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 440 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 880 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 260 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 151 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 866 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 140 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 499 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 484 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 585 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 905 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 428 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 975 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 48 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 494 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 355 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 951 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 460 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 655 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 414 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 615 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 355 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 171 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 42 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 545 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 169 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 659 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 782 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 748 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 374 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 354 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 650 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 540 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 585 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 128 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 623 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 885 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 730 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 611 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 342 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 95 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 381 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 644 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 162 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 879 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 880 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 889 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 396 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 465 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 22 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 608 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 534 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 601 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 81 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 868 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 702 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 140 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 754 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 819 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 795 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 817 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 204 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 717 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 335 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 262 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 879 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 88 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 99 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 610 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 507 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 389 >> 01_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 01 519 >> 01_log.log
