C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 792 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 479 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 327 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 878 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 405 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 966 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 623 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 386 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 828 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 579 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 237 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 251 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 569 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 293 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 542 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 373 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 276 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 557 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 190 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 380 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 947 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 959 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 82 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 797 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 308 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 4 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 79 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 594 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 783 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 164 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 868 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 828 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 71 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 763 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 554 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 97 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 617 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 258 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 470 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 292 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 584 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 225 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 623 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 422 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 19 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 39 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 784 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 725 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 518 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 975 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 216 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 625 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 58 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 502 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 503 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 679 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 279 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 821 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 674 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 88 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 465 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 588 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 839 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 788 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 24 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 84 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 195 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 922 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 26 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 253 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 642 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 946 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 283 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 405 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 381 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 862 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 516 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 727 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 326 >> 02_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 02 817 >> 02_log.log
