C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 548 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 699 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 796 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 71 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 521 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 260 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 619 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 694 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 6 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 215 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 946 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 159 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 442 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 706 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 147 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 693 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 435 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 755 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 478 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 701 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 659 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 275 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 800 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 922 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 38 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 961 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 785 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 252 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 453 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 932 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 852 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 416 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 401 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 723 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 764 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 218 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 121 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 965 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 3 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 618 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 591 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 871 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 781 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 949 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 46 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 264 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 625 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 208 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 927 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 13 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 138 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 544 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 255 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 440 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 458 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 242 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 261 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 859 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 658 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 343 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 895 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 834 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 459 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 259 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 592 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 911 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 642 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 32 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 573 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 258 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 315 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 649 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 713 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 210 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 924 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 134 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 525 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 625 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 556 >> 03_log.log
C:\Users\Administrator\anaconda3\python.exe "C:\Users\Administrator\Documents\szakdolgozat\szakdolgozat.py" 03 527 >> 03_log.log
